apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lw-faktory
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage.models }}