apiVersion: v1
kind: Service
metadata:
  name: lw-faktory
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lw-faktory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboard.port }}
      name: {{ .Values.service.dashboard.name }}
    - port: {{ .Values.service.api.port }}
      name: {{ .Values.service.api.name }}
  selector:
    {{- include "lw-faktory.selectorLabels" . | nindent 4 }}
